/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tmc' at '1/18/17 9:31 AM' with Gradle 3.1
 *
 * @author tmc, @date 1/18/17 9:31 AM
 */
public class Library {
	
    public static void main(String[] args){
    	System.out.println("=================================================================")
	    System.out.println("Welcome to Algorithms and Data Structures! @ coded by Hung Huynh");
	    System.out.println("=================================================================")
    }

    public boolean someLibraryMethod() {
        return true;
    }
}
